Update get_eurostat_json.R
rOpenGov/eurostat pull request #262
Opened 2023-06-09 08:44 UTC by ake123

Return informative get_eurostat_json error messages to the user #261

2023-06-09 13:48 UTC, pitkant commented
It seems that the problem described in #260 is now solved. Great. However, I couldn't use examples mentioned there to debug this new code. Boo.

I could do something by providing a wrong parameter to the API. E.g. this erroneous query (it uses fromTimePeriod instead of the correct sinceTimePeriod):

```
get_eurostat("TIPSHO40", filter = list(fromTimePeriod = 2005, untilTimePeriod = 2007))
```

Procudes this url: https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/TIPSHO40?fromTimePeriod=2020&untilTimePeriod=2021&format=JSON&lang=EN
Which produces the following error:

```
{ "error": [{"status": 400,"id": 150,"label": "INVALID_QUERY_DIMENSION: Query is invalid as per its structure's definition. Dimension \"FROMTIMEPERIOD\" is not defined"}]}
```

When I do the query in R, I get the following output:

```
get_eurostat("TIPSHO40", filter = list(fromTimePeriod = 2005, untilTimePeriod = 2007))
Request failed [400]. Retrying in 1.7 seconds...
Request failed [400]. Retrying in 4 seconds...
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  The requested url cannot be found within the get_eurostat_json function:
                  Client Error - 100 No results found 
                  Description - The requested resource is not available. https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/TIPSHO40?fromTimePeriod=2005&untilTimePeriod=2007&format=JSON&lang=EN
```

So it actually gets the HTTP status correctly in the old code ("Request failed [400]") but it prints a wrong message after it ("Client Error - 100 No results found").

Could you fix the code contribution so that

1. The http request would read and save the error message (http status, id and label) from the response.
2. The message would return the status, id and label that were saved in the memory. Now it's returning hardcoded messages.

2023-06-12 08:50 UTC, ake123 commented
Solved! Feel free to comment!

2023-06-13 13:59 UTC, ake123 commented
Now updated the recommended changes

2023-06-13 14:51 UTC, pitkant commented on R/get_eurostat_json.R
> +  	  http://ec.europa.eu/eurostat/web/prodcom/data/excel-files-nace-rev.2"
I actually tested all the URLs listed here. The 1st and the 3rd one are broken and the 2nd one is to BulkDownloadListing which is anyway going away in October 2023. Maybe this message should be rewritten, maybe as a general directions towards reading function documentation or checking Eurostat website datasets.

2023-06-13 14:55 UTC, pitkant commented on R/get_eurostat_json.R
> +     }
This is a stop function: if `http::http_error(resp)` is true (status code 400 or above), then stop function will run and that will prevent the functions below from running. So actually the `if (status == 400)`, `if (status == 500)` and `if (status == 416)` sections are left unused now. This must be corrected if we want different error messages to have their own if-else sections. (although I think that might be unnecessary when we have generic error message template that takes the codes from the response)

2023-06-13 14:58 UTC, pitkant commented on R/get_eurostat_json.R
> +                       msg)))
Maybe different id and label explanations could be stored in a data frame object that could be references like a VLOOKUP table in Excel? It seems like a lot of code-repetition when labels are put here like this.

2023-06-13 14:58 UTC, pitkant requested changes
I reviewed your code with the line-specific comments that should be listed here.

Additionally, the empty status message problem still persists and there are no unit tests checking if things work.

```
> get_eurostat("", filter = list(fromTimePeriod = 2005, untilTimePeriod = 2007))
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  Status :   , error id :   No results found , label :  
```

2023-06-13 15:01 UTC, pitkant commented on R/get_eurostat_json.R
> +     }
This comment read as outdated but the only difference from the more recent get_eurostat_json.R file is the removal of print(httr::headers(resp)) and comments from lines 124-126

2023-06-14 11:37 UTC, ake123 commented on R/get_eurostat_json.R
> +                       msg)))
`http::content(resp)$error[[1]]$id`  is for fault code. Of course I can remove the `httr::content(resp)$error[[1]]$status` to replace it with `status`

2023-06-14 11:45 UTC, pitkant commented on R/get_eurostat_json.R
> +                       msg)))
Oh yeah, that's right. Anyway it might be good to save the response to a single object and read that object instead of calling httr::content function again and again, which adds a small overhead.

2023-06-14 13:24 UTC, ake123 commented
The error message is now replaced as follows

```
> get_eurostat("", filter = list(fromTimePeriod = 2005, untilTimePeriod = 2007))
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors, :
Failure to get data. Status code: 404 Some datasets are not accessible via the eurostat
interface. You can try to search the data manually from the comext
database athttps://ec.europa.eu/eurostat/comext/newxtweb/ or API data query at
https://wikis.ec.europa.eu/display/EUROSTATHELP/API+Statistics+-+data+query
```

2023-06-14 14:05 UTC, pitkant commented on R/get_eurostat_json.R
> +  	  http://ec.europa.eu/eurostat/web/prodcom/data/excel-files-nace-rev.2"
I unresolved this comment as it's about the same lines as before but it's of course related to the most recent version [a86d575](https://github.com/rOpenGov/eurostat/pull/262/commits/a86d575bd2482ade8cb09b7e1a51ef3102247660) in the PR.

- I don't think it's a good idea to link to API data query resources as eurostat package itself is querying the API. A better alternative would be https://ec.europa.eu/eurostat/web/main/data/database
- There should be a space between "at" and "https" in row 111
- I think it would be good to remove spaces from the message, they don't print nicely
- Remove also the dot from the beginning of the msg

```
Status :  400 Bad request , error id :  150 Semantic error , label :  INVALID_QUERY_DIMENSION: Query is invalid as per its structure's definition. Dimension "FROMTIMEPERIOD" is not defined 
 . Some datasets are not accessible via the eurostat
            interface. You can try to search the data manually from the comext
  	    database athttps://ec.europa.eu/eurostat/comext/newxtweb/ or API data query at
  	  https://wikis.ec.europa.eu/display/EUROSTATHELP/API+Statistics+-+data+query
```

2023-06-14 14:21 UTC, pitkant commented on R/get_eurostat_json.R
> +                       msg)))
What I meant was that different codes could be in a data.frame or a vector where they could be looked up.

2023-06-14 14:28 UTC, ake123 commented on R/get_eurostat_json.R
> +                       msg)))
Will look into it

2023-06-19 13:21 UTC, ake123 commented on R/get_eurostat_json.R
> +                       msg)))
The different codes are in data frame and they can be looked up

2023-06-20 09:25 UTC, merged